### ISSUE TITLE
[Question] Can this driver extension be used with karabiner-elements?

### ISSUE THREAD

**Issue by jakecast** [pqrs-org/Karabiner-DriverKit-VirtualHIDDevice#3]
If I build this and active the driver extension, can this be used with Karabiner-Elements (and offload the existing kext) or would that require updating Karabiner-Elements updates to point at this new driver as well?

Thank you!
Jake

**Comment by tekezo** [comment]
I'm making this driver in order to replace kext in Karabiner-Elements.
But at the moment, we need to modify Karabiner-Elements code to use this driver.
Please wait for Karabiner-Elements update.
