### ISSUE TITLE
Instructions for building without entitlements

### ISSUE THREAD

**Issue by kokroo** [pqrs-org/Karabiner-DriverKit-VirtualHIDDevice#31]
Hello,

The previous versions of the repo had instructions for building without gaining entitlements (after disabling SIP).
Is it possible to add a section in the README detailing those steps?

It will be useful for developing and testing locally.
Thanks!

**Comment by kokroo** [comment]
@tekezo Hello tekezo, thank you for the quick reply.

Would a team still need to contact Apple before releasing the driver for distribution (not just development)?
I am asking this for my information, and to help anyone coming here through Google searches.

**Comment by tekezo** [comment]
I think this Additional Capabilities section is not visible with a regular Apple ID, so special permissions from Apple might still be necessary for distribution.
https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/blob/main/docs/images/additional-capabilities@2x.png

**Comment by kokroo** [comment]
@tekezo I will try it myself soon and report back here with my experience. Cheers!

**Comment by kokroo** [comment]
@tekezo I will try it myself soon and report back here with my experience. Cheers!
