### ISSUE TITLE
Running into 39 and 54 error when executing tests

### ISSUE THREAD

**Issue by catwang01** [pqrs-org/Karabiner-DriverKit-VirtualHIDDevice#33]
I installed 5.0.0 and tested it with instructions in the doc. I ran into 39 and 54 errors:

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/299f3588-6473-45bf-9b46-50ab066a879e">

<img width="1382" alt="image" src="https://github.com/user-attachments/assets/7ce51872-a8a9-4178-8a0f-179edad43854">

Does anyone know what I can do?

I'm using Mac 14.6, M3 chip.

**Comment by tekezo** [comment]
54 is `Connection reset by peer` error.
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/intro.2.html

First, please check the following.

If there are no issues, please check the Console's Crash Report to see if the process is crashing.
If there's no issue there either, it's highly likely that third-party security software is blocking the communication.

## Check `Karabiner-VirtualHIDDevice-Daemon` is running

```shell
$ ps axuw | grep Karabiner-VirtualHIDDevice-Daemon

root             96338   0.1  0.0 410952352   3904   ??  Ss   Fri09AM   9:26.89 /Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon
```
## Check the socket file exists

```shell
sudo ls -l /Library/Application\ Support/org.pqrs/tmp/rootonly/vhidd_server/

total 0
srwxr-xr-x  1 root  wheel  0 Nov 22 09:28 180a22dbcd0d2918.sock
```

**Comment by catwang01** [comment]
Thanks for your quick reply! It's really helpful!

I realized this issue should be caused by launching multiple daemon instances. I killed other daemons and only left one and it worked.

Closed this.
