### ISSUE TITLE
Question: building without a Developer ID?

### ISSUE THREAD

**Issue by thoelze1** [pqrs-org/Karabiner-DriverKit-VirtualHIDDevice#6]
According to its readme, Karabiner-VirtualHIDDevice can be built without a code signature from apple. Will you ever publish a version of Karabiner-DriverKit-VirtualHIDDevice that can be built without a signature?

**Comment by tekezo** [comment]
No, we cannot do it.
Xcode requires Developer ID to build driver extension.

**Comment by thoelze1** [comment]
Does that mean that Karabiner-VirtualHIDDevice also can't be built without a Developer ID?

**Comment by tekezo** [comment]
You can build Karabiner-VirtualHIDDevice without Developer ID.
But it uses kext and you cannot use kext since Big Sur (11.0).
