### ISSUE TITLE
Activation failed with error 9

### ISSUE THREAD

**Issue by kakashidinho** [pqrs-org/Karabiner-DriverKit-VirtualHIDDevice#8]
Hi,
I compiled your v0.11.0 code and run the ext manager app. However, when clicking activate button, the ouput said “the operation couldn’t be completed. OSSystemExtensionErrorDomain error 9”
Not sure what’s wrong. Maybe because I dont have driverkit entitlement.
Just asking if you have any insight.

**Comment by tekezo** [comment]
You have to disable SIP to install driver extension if you don't have driverkit entitlement yet.
Did you disable SIP on your test machine?
https://developer.apple.com/documentation/driverkit/debugging_and_testing_system_extensions

**Comment by kakashidinho** [comment]
It was already disabled. I double checked via “csrutil status”

**Comment by kakashidinho** [comment]
Seems like this is machine dependent. I failed to activate on one machine but successfully activated on another one.
Anw, I can debug the driver extension using lldb. However I don't see any log in the console. Where to view the log written by driver extension?
Thanks,

**Comment by tekezo** [comment]
You can show `log` command.
https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/blob/master/DEVELOPMENT.md#log-messages
