### ISSUE TITLE
 Constant crashes with EXC_BAD_ACCESS (SIGSEGV) in Karabiner Elements 13.0.0

### ISSUE THREAD

**Issue by dredhorse** [pqrs-org/Karabiner-DriverKit-VirtualHIDDevice#9]
I have constant crashes in the driver.

`Process:               org.pqrs.Karabiner-DriverKit-VirtualHIDDevice [5942]
Path:                  /Library/SystemExtensions/*/org.pqrs.Karabiner-DriverKit-VirtualHIDDevice
Identifier:            org.pqrs.Karabiner-DriverKit-VirtualHIDDevice
Version:               1.0.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
Responsible:           org.pqrs.Karabiner-DriverKit-VirtualHIDDevice [5942]
User ID:               270

Date/Time:             2020-10-06 09:41:55.015 +0200
OS Version:            Mac OS X 10.15.6 (19G73)
Report Version:        12
Anonymous UUID:        D79F4525-BACA-A88F-A335-8620849066AA

Time Awake Since Boot: 2500 seconds

System Integrity Protection: disabled

Crashed Thread:        1  Dispatch queue: org_pqrs_Karabiner_DriverKit_VirtualHIDKeyboard-Default

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [5942]

Application Specific Information:
dyld2 mode

Thread 0:
0   libsystem_kernel.dylib        	0x0000000105d77302 __semwait_signal_nocancel + 10
1   libsystem_c.dylib             	0x0000000105ca2678 nanosleep$NOCANCEL + 185
2   libsystem_c.dylib             	0x0000000105cbf450 sleep$NOCANCEL + 41
3   libdispatch.dylib             	0x0000000105bf77b0 _dispatch_queue_cleanup2 + 156
4   libsystem_pthread.dylib       	0x0000000105e6d921 _pthread_tsd_cleanup + 164
5   libsystem_pthread.dylib       	0x0000000105e67206 _pthread_exit + 70
6   libsystem_pthread.dylib       	0x0000000105e68033 pthread_exit + 42
7   libdispatch.dylib             	0x0000000105bf33a0 dispatch_main + 99
8   com.apple.DriverKit           	0x0000000105a21bad DriverExecutableMain + 66
9   libdyld.dylib                 	0x0000000105c5ec01 start + 1

Thread 1 Crashed:: Dispatch queue: org_pqrs_Karabiner_DriverKit_VirtualHIDKeyboard-Default
0   org.pqrs.Karabiner-DriverKit-VirtualHIDDevice	0x0000000105a02653 org_pqrs_Karabiner_DriverKit_VirtualHIDKeyboard::setReport(IOMemoryDescriptor*, IOHIDReportType, unsigned int, unsigned int, OSAction*) + 87
1   com.apple.HIDDriverKit        	0x0000000105a91ab8 IOHIDDevice::_ProcessReport_Impl(HIDReportCommandType, IOMemoryDescriptor*, IOHIDReportType, unsigned int, unsigned int, OSAction*) + 88
2   com.apple.HIDDriverKit        	0x0000000105aa26b0 IOHIDDevice::_ProcessReport_Invoke(IORPC, OSMetaClassBase*, void (*)(OSMetaClassBase*, HIDReportCommandType, IOMemoryDescriptor*, IOHIDReportType, unsigned int, unsigned int, OSAction*)) + 142
3   com.apple.DriverKit           	0x0000000105a21241 invocation function for block in OSMetaClassBase::Invoke(IORPC) + 117
4   com.apple.DriverKit           	0x0000000105a20eb1 OSMetaClassBase::Invoke(IORPC) + 717
5   com.apple.DriverKit           	0x0000000105a21739 Server(void*, mach_msg_header_t*, mach_msg_header_t*) + 584
6   com.apple.DriverKit           	0x0000000105a22acd uiomachchannel(void*, dispatch_mach_reason_t, dispatch_mach_msg_s*, int) + 149
7   libdispatch.dylib             	0x0000000105bfce55 _dispatch_mach_msg_invoke + 435
8   libdispatch.dylib             	0x0000000105becf06 _dispatch_lane_serial_drain + 263
9   libdispatch.dylib             	0x0000000105bfd9a8 _dispatch_mach_invoke + 481
10  libdispatch.dylib             	0x0000000105becf06 _dispatch_lane_serial_drain + 263
11  libdispatch.dylib             	0x0000000105beda1d _dispatch_lane_invoke + 414
12  libdispatch.dylib             	0x0000000105beebba _dispatch_workloop_invoke + 1813
13  libdispatch.dylib             	0x0000000105bf6fdf _dispatch_workloop_worker_thread + 596
14  libsystem_pthread.dylib       	0x0000000105e68c0a _pthread_wqthread + 290
15  libsystem_pthread.dylib       	0x0000000105e6e0cb start_wqthread + 15

Thread 2:
0   libsystem_pthread.dylib       	0x0000000105e6e0bc start_wqthread + 0

Thread 3:
0   libsystem_kernel.dylib        	0x0000000105d7758a __sigsuspend_nocancel + 10
1   libdispatch.dylib             	0x0000000105bf7872 _dispatch_sigsuspend + 36
2   libdispatch.dylib             	0x0000000105bf784e _dispatch_sig_thread + 55

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0xaaaaaaaaaaaaaaaa  rbx: 0x000070000fdebea8  rcx: 0xc35266e3aeb0007d  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x000070000fdebef0  rsp: 0x000070000fdebe90
   r8: 0x0000000000000008   r9: 0x0000000000000000  r10: 0x000000000000000a  r11: 0x0000000000000246
  r12: 0x00000000e00002c7  r13: 0x0000000000000000  r14: 0x0000600000578058  r15: 0x0000000000000000
  rip: 0x0000000105a02653  rfl: 0x0000000000010282  cr2: 0x00007fcf14700018
  
Logical CPU:     8
Error Code:      0x00000000
Trap Number:     13

Binary Images:
       0x1059fe000 -        0x105a05fff +org.pqrs.Karabiner-DriverKit-VirtualHIDDevice (1.0.0 - 1.0.0) <D0FF0026-79D1-3E01-8BC7-DFA4A23DF4DA> /Library/SystemExtensions/*/org.pqrs.Karabiner-DriverKit-VirtualHIDDevice
       0x105a1e000 -        0x105a4bff7  com.apple.DriverKit (1.0 - ???) <450A6B3B-881A-3BB2-A57F-DDE9F8A2D01B> /System/DriverKit/System/Library/Frameworks/DriverKit.framework/DriverKit
       0x105a8e000 -        0x105aaefff  com.apple.HIDDriverKit (1.0 - 1) <189B7F0A-BE8C-3900-8B97-038A5ECBDD53> /System/DriverKit/System/Library/Frameworks/HIDDriverKit.framework/HIDDriverKit
       0x105acb000 -        0x105adcff7  libc++.dylib (902.1) <1B680330-0CE7-309C-8745-40B0D01BA5C6> /System/DriverKit/usr/lib/libc++.dylib
       0x105af5000 -        0x105af6ff7  libSystem.dylib (1281.100.1) <95F03C1C-CA96-3C7C-B573-A9208F8441D0> /System/DriverKit/usr/lib/libSystem.dylib
       0x105b03000 -        0x105b0aff7  libcompiler_rt.dylib (101.2) <AC511827-4908-314B-9337-659A31326E96> /System/DriverKit/usr/lib/system/libcompiler_rt.dylib
       0x105b1b000 -        0x105bbdfd7  libcorecrypto.dylib (866.140.1) <4672BE78-40B4-3FAE-9CB2-6F620EAEC208> /System/DriverKit/usr/lib/system/libcorecrypto.dylib
       0x105be6000 -        0x105c28fff  libdispatch.dylib (1173.100.2) <4DBEB483-1CD4-394E-84EB-4FA9E6ECFC67> /System/DriverKit/usr/lib/system/libdispatch.dylib
       0x105c5e000 -        0x105c71ff7  libdyld.dylib (750.6) <803107D6-745C-366A-80C5-922C4072BF1C> /System/DriverKit/usr/lib/system/libdyld.dylib
       0x105c85000 -        0x105c85fff  libmacho.dylib (959.0.1) <95882E52-5C07-3C59-AB35-A97303344204> /System/DriverKit/usr/lib/system/libmacho.dylib
       0x105c8d000 -        0x105c8dfff  libsystem_blocks.dylib (74) <26482DA6-E097-3DF1-8288-542CB26A2917> /System/DriverKit/usr/lib/system/libsystem_blocks.dylib
       0x105c9d000 -        0x105d22ff7  libsystem_c.dylib (1353.100.2) <36450845-2ABF-30A4-BDB0-8A93A85F1A4A> /System/DriverKit/usr/lib/system/libsystem_c.dylib
       0x105d57000 -        0x105d86fff  libsystem_kernel.dylib (6153.141.1) <470D9C8C-50AA-3423-91CB-2C850E0799B3> /System/DriverKit/usr/lib/system/libsystem_kernel.dylib
       0x105da8000 -        0x105df9fef  libsystem_m.dylib (3178) <C43EB721-C9E9-33D7-940D-CAAC804C51FB> /System/DriverKit/usr/lib/system/libsystem_m.dylib
       0x105e0f000 -        0x105e39fff  libsystem_malloc.dylib (283.100.6) <B825C6F4-355A-3A4A-B28A-B32106D8C9B3> /System/DriverKit/usr/lib/system/libsystem_malloc.dylib
       0x105e4f000 -        0x105e57ff7  libsystem_platform.dylib (220.100.1) <CE50A8D4-93DC-385B-8228-4FDBE1F1BAC8> /System/DriverKit/usr/lib/system/libsystem_platform.dylib
       0x105e66000 -        0x105e71fff  libsystem_pthread.dylib (416.100.3) <DD9525F3-A4A2-35F5-A070-85006347AC71> /System/DriverKit/usr/lib/system/libsystem_pthread.dylib
       0x105e85000 -        0x105e8afff  libsystem_trace.dylib (1147.120) <1D096E7A-B37C-30E9-AB0E-157FDCDB5146> /System/DriverKit/usr/lib/system/libsystem_trace.dylib
       0x105e98000 -        0x105eb0fff  libc++abi.dylib (902) <1CE8C2A0-58D4-3C23-A9F2-968B0C3A2E31> /System/DriverKit/usr/lib/libc++abi.dylib
       0x105ed1000 -        0x105edcff7  com.apple.USBDriverKit (1.0 - 1) <11F79371-19D5-3EF3-AB3D-5E0E3CFFAFFF> /System/DriverKit/System/Library/Frameworks/USBDriverKit.framework/USBDriverKit
       0x1073d6000 -        0x107467f47  dyld (750.6) <34A11073-9E4C-38C3-9293-7D566ABAE8B6> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 3714
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=5196K resident=0K(0%) swapped_out_or_unallocated=5196K(100%)
Writable regions: Total=534.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=534.0M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                           140.2M       14 
MALLOC guard page                   24K        4 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        4 
Stack                             9752K        4 
__DATA                             424K       27 
__DATA_CONST                       216K       21 
__DATA_DIRTY                        12K        3 
__LINKEDIT                        1664K       22 
__TEXT                            3536K       21 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                            595.4M      124 
TOTAL, minus reserved VM space   211.4M      124 

System Profile:
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Boot Volume File System Type: apfs
PCI Card: Intel UHD Graphics 630 (Desktop 9 Series), Display controller, Built In
PCI Card: Intel Z390 USB 3.1 xHCI Host Controller, USB controller, Built In
PCI Card: Intel Z390 SATA Controller, SATA controller, Built In
PCI Card: Apple High Definition Audio Controller, Audio device, Built In
PCI Card: Intel Z390 SPI Controller, Serial bus controller, Built In
PCI Card: Intel I219V7 PCI Express Gigabit Ethernet, Ethernet controller, Built In
PCI Card: BCM4360 802.11ac Wireless Network Adapter, Network controller, Slot 4
PCI Card: Samsung 970 Evo NVMe SSD, Non-Volatile memory controller, PCIe M.2 Slot 1
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 3200 MHz, 8502, 3200 C16 Series
Memory Module: BANK 1/ChannelA-DIMM1, 8 GB, DDR4, 3200 MHz, 8502, 3200 C16 Series
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 3200 MHz, 8502, 3200 C16 Series
Memory Module: BANK 3/ChannelB-DIMM1, 8 GB, DDR4, 3200 MHz, 8502, 3200 C16 Series
USB Device: Ultra Fit
USB Device: Hub
USB Device: 4-Port USB 3.0 Hub
USB Device: 4-Port USB 3.0 Hub
USB Device: Logitech BRIO
USB Device: USB2.0 Hub
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Hub [MTT]
USB Device: farbwerk 360
USB Device: farbwerk 360
USB Device: VISION
USB Device: D5 NEXT
USB Device: aquaero
USB Device: USB2.0 Hub
USB Device: Hub
USB Device: Plantronics BT600
USB Device: Jabra Link 370
USB Device: Jabra Evolve 75
USB Device: Composite Device
USB Device: 4-Port USB 2.0 Hub
USB Device: RODE NT-USB
USB Device: Razer BlackWidow Tournament Edition Chroma
USB Device: 4-Port USB 2.0 Hub
USB Device: USB Receiver
USB Device: Stream Deck
USB Device: LUXAFOR FLAG
Serial ATA Device: Samsung SSD 850 EVO 250GB, 250,06 GB
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500,11 GB
Serial ATA Device: ST2000LX001-1RG174, 2 TB
Serial ATA Device: CT2000MX500SSD1, 2 TB
Model: iMac19,1, BootROM 1037.120.79.0.0, 8 processors, 8-Core Intel Core i9, 3,6 GHz, 32 GB, SMC 2.46f12
Graphics: Radeon RX 5700 XT 50th Anniversary, Radeon RX 5700 XT 50th Anniversary, spdisplays_pcie_device, 8 GB
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.1)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
`

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at Driver version 1.2.0.
https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/commits/master

I'll update Karabiner-Elements beta with the latest driver.

**Comment by tekezo** [comment]
Karabiner-Elements v13.0.12 fixed this issue.
Please confirm the latest beta version.

How to upgrade Karabiner-Elements to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>
